all:
  children:
    proxmox:
      hosts:
        pve01:
#          ansible_host: 10.0.0.175
          ansible_host: 10.0.0.176
          ansible_user: root 
          ansible_python_interpreter: /usr/bin/python3
#          proxmox_hostname: "hagrid.local"
          proxmox_hostname: "harry.local"
#          acme_domain: "hagrid.robaalbue.com"
          acme_domain: "harry.robaalbue.com"
